===  Функциональные требования

==== Предварительные условия

Наличие договора(ов) с агрегатором(ами) платежей и средств использования системы электронных платежей этого агрегатора.
Наличие договора(ов) с логистическими компаниями по доставке товаров от продавцов к покупателям с возможностью автоматического отслеживания прохождения доставки заказа с использованием средств, предоставляемых логистическими компаниями. При этом редполагается указание сервиса при отправке продавцом товара покупателю.

==== Требования

. Возможность для продавца создавать, редактировать, публиковать, архивировать (удалять из видимости), восстанавливать и удалять карточки товаров/услуг.
. Возможность для покупателя просматривать объявления, осуществлять по ним классификационный,  атрибутивный и полнотекстовой поиск.
. Поддержка медиаконтента (изображений, видео), описаний, атрибутов, тегирования товаров и услуг.
. Возможность для покупателя оформлять заказы средствами сервиса с фиксацией условий сделки и резервированием заказанного товара.
. Информирование продавца о новом заказе.
. Возможность для покупателя вести диалог с продавцом по конкретным объявлениям и с сервисом по условиям работы сервиса.
. Средства регистрации продавцов и покупателей и их контактов на площадке сервиса, с возможностью полной и неполной идентификации продавцов.
. Модерация объявлений перед публикацией.
. Возможность для зарегистрированного покупателя вести самостоятельную одноуровневую классификацию товаров (целевые списки).
. Создание механизмов оплаты заказов покупателями средствами сервиса с использованием систем электронных платежей внешнего агрегатора, с учётом удержания комиссии в пользу сервиса и оформлением платежей в соответствии с законодательством.
. Публикация средствами сервиса единой публичной оферты (условий обслуживания) для продавцов и покупателей.
. Возможность категоризации продавцов и покупателей.
. Возможность создания специальных условий работы с сервисом (размер комиссии, сроки её поступления) для указанных категорий продавцов или отдельных продавцов.
. Возможность отслеживания доставки товаров покупателям средствами сервиса с использованием средств, предоставляемых для этого логистическими компаниями, ответственными за доставку.
. Формирование отчётности для продавцов и администрации сервиса о сделках, начислениях и выплатах, с возможностью фильрации по категориям товаров и продавцов, периодам, статусам.
