=== Описание концептуальной архитектуры

Система имеет сервисную архитектуру и реализуется в виде укрупнённых сервисов с использованием:

* синхронных взаимодействий (REST/gRPC)
* асинхронных взаимодействий (Kafka)
* polling для пользовательских сообщений (без realtime/WebSocket)
* для поддержки географического охвата геораспределения через GeoDNS (Москва / Краснодар), а также для доставки медиа-контента поддерживает CDN с узлами в Санкт-Петербурге и Казани.

Система состоит из следующих сервисов:

. Сервис авторизации, опирающийся на Базу Данных Авторизации и поддерживающий аутентификацию, авторизацию и поддержание сессий работы пользователей.
. Сервис профилей пользователей, опирающийся на Базу Данных Пользователей и поддерживающий информацию о них, целевые списки (wish-листы) пользователей, получаемую информацию о поведении.
. Сервис объявлений, включающий Базу Данных Объявлений, содержащую основные данные объявлений. Поддерживает актуальное состояние и резервирование товаров по объявлениям. Через него осуществляется обмен сообщениями между покупателями и продавцами.
. Сервис поиска, связанный с сервисом объявлений, и использующий отдельную или совмещённую с сервисом объявлений Базу Данных, настроенную для параметрического и текстового поиска. Также реализует функционал рекомендаций покупателям.
. Сервис заказов, включающий Базу Данных Заказов, содержащую информацию о товарном, логистическом и финансовом состоянии заказов
. Сервис доставки отвечает за связь с API логистических компаний и формирование (при необходимости - моделирование) данных о транспортировке заказов.
. Сервис платежей отвечает за обработку платежей через связь с API платежных сервисов.
. Сервис расчётов, учитывающий финансовую часть сделок и комиссию торговой площадки.
. Аналитический сервис предоставляет отчётную информацию о потоке заказов и финансовых показателях системы, рассылает уведомления пользователям.
. Медиа-сервис поддержки CDN.

Сервисы взаимодействуют между собой через общий брокер сообщений ("шину данных"). С внешними поставщиками данных (платёжные и логистические сервисы) соответствующие сервисы системы взаимодействуют напрямую. Отдельные сервисы также могут взаимодействовать синхронно напрямую, если этого требует логика бизнес-процесса. Такие взаимодействия будут специально описаны в соответствующих частях.

Пользователи взаимодействуют с системой через веб-интерфейс или мобильное приложение (фронтенд). Фронтенд и, при необходимости, другие внешние информационные системы обмениваются с системой данными посредством API с единой точкой входа.

Информирование пользователей осуществляется через публикацию сообщений в личных кабинетах. Диалоги между покупателями и продавцами также привязываются к сервису объявлений и ведутся в асинхронном режиме.
