=== Описание концептуальной архитектуры

Система имеет сервисную архитектуру и состоит из следующих сервисов:

. Сервис авторизации, опирающийся на Базу Данных Пользователей и поддерживающий аутентификацию, авторизацию и поддержание сессий работы пользователей.
. Сервис объявлений, включающий Базу Данных Объявлений, содержащую основные данные объявлений. Поддерживает актуальное состояние и резервирование товаров по объявлениям.
. Сервис поиска, связанный с сервисом объявлений, и использующий отдельную или совмещённую с сервисом объявлений Базу Данных, настроенную для параметрического и текстового поиска.
. Сервис заказов, включающий Базу Данных Заказов, содержащую информацию о товарном, логистическом и финансовом состоянии заказов
. Сервис доставки отвечает за связь с API логистических компаний и формирование (при необходимости - моделирование) данных о транспортировке заказов.
. Сервис платежей отвечает за обработку платежей через связь с API платежных сервисов.
. Аналитический сервис предоставляет отчётную информацию о потоке заказов и финансовых показателях системы.

Сервисы взаимодействуют между собой через общий брокер сообщений ("шину данных"). С внешними поставщиками данных (платёжные и логистические сервисы) соответствующие сервисы системы взаимодействуют напрямую.

Пользователи взаимодействуют с системой через веб-интерфейс или мобильное приложение (фронтенд). Фронтенд и, при необходимости, другие внешние информационные системы обмениваются с системой данными посредством API с единой точкой входа.

Информирование пользователей осуществляется через публикацию сообщений в личных кабинетах.
