=== Пользователи решения

Для работы с системой устанавливаются следующие роли пользователей:

==== Внешние пользователи
. Покупатель - пользователь, которому доступен поиск товаров по объявлениям, просмотр объявлений, формирование и оплата заказов, получение отчётов по своим покупкам и оплатам. Для осуществления взаимодействия с ним идентифицируется в системе, по крайней мере, адресом электронной почты или номером телефона.
. Продавец - пользователь, которому доступно размещение, редактирование и архивирование (логичкское удаление) объявлений (в части редактирования и архивирования - только для своих объявлений), отчёты по своим объявлениям и их оплате. Идентифицируется адресом(ами) электронной почты, номером(ами) телефона и реквизитами для осуществления платежей.
* Гость — незарегистрированнй (неавторизованный) пользователь, просматривает каталог без оформления заказов

==== Внутренние пользователи
. Модератор - пользователь, контролирующий контент и взаимодействующий с внешними пользователями
. Администратор - пользователь, осуществляющий технические настройки и поддержание работоспособности системы.
. Аналитик - пользователь, анализирующий данные и формирующий отчеты

==== Внешние системы
* Платежные системы — обрабатывают платежи
* Службы доставки — обрабатывают доставку заказов
