=== Описание системы

Рассматриваемая система является электронной торговой площадкой, предоставляющей сервис публикации объявлений о продаже товаров и предоставлении услуг с доставкой товаров и проведением оплаты.

==== Предварительные условия

Наличие договора(ов) с агрегатором(ами) платежей и средств использования системы электронных платежей этого агрегатора (API).
Наличие договора(ов) с логистическими компаниями по доставке товаров от продавцов к покупателям с возможностью автоматического отслеживания прохождения доставки заказа с использованием средств, предоставляемых логистическими компаниями  (API). При этом предполагается указание сервиса при отправке продавцом товара покупателю в пункте приёма товара логистической компанией.

==== Ограничения
Система разрабатывается для работы в европейской части РФ: Центральном, Северо-западном (кроме Калининградской области), Приволжском и Южным федеральных округах, определяемой сетевой и транспортной доступностью.

Не рассматриваются проблемы  взаимодействия с зарубежными пользователями и продажа/покупка в валюте, отличной от российского рубля.

Не рассматриваются проблемы и риски, связанные с финансовой (налоговой) отчётностью владельца системы, и соответствующий функционал.