=== Описание системы

Рассматриваемая система является электронной торговой площадкой, предоставляющей сервис публикации объявлений о продаже товаров и предоставлении услуг с доставкой товаров и проведением оплаты.
Система разрабатывается для работы в западной части РФ (Центральном, частях Северо-западного и Приволжского федеральных округов), определяемой сетевой и транспортной доступностью. В случае успешной реализации системы возможно поэтапное расширение её вплоть до охвата всей территории РФ. При проектировании и разработке системы следует учитывать возможность подобного масштабирования.

==== Предварительные условия

Наличие договора(ов) с агрегатором(ами) платежей и средств использования системы электронных платежей этого агрегатора (API).
Наличие договора(ов) с логистическими компаниями по доставке товаров от продавцов к покупателям с возможностью автоматического отслеживания прохождения доставки заказа с использованием средств, предоставляемых логистическими компаниями  (API). При этом предполагается указание сервиса при отправке продавцом товара покупателю в пункте приёма товара логистической компанией.

